export const GENERAL_QUESTIONS_TOPIC_ID = 5;
export const ABOUT_YOUR_HEALTH_INFO_TOPIC_ID = 6;
export const ABOUT_PAYING_YOUR_BILLS = 7;

// export enum TopicId {
//   GENERAL_QUESTIONS = 5,
//   ABOUT_YOUR_HEALTH_INFO = 6,
//   ABOUT_PAYING_YOUR_BILLS = 7,
// }
